language: "go"
go:
  - "1.10"

install:
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script: 
  - make lint
  - go test ./... -race -cover -coverprofile=coverage.out
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
